executors:
  ubuntu:
    parameters:
      class:
        description: The resource class. Default is medium.
        type: enum
        enum: ["medium", "large", "xlarge", "2xlarge"]
        default: "medium"
      version:
        description: the version of the machine. Default is 2204
        type: string
        default: "2204"
      tag:
        description: the tag of the machine. Default is current
        type: string
        default: "current"
      with_docker_layer_caching:
        description: should we use Docker Layer Caching mechanism. Default is false
        type: boolean
        default: false
    machine:
      image: "ubuntu-<< parameters.version >>:<< parameters.tag >>"
      docker_layer_caching: << parameters.with_docker_layer_caching >>
    resource_class: "<< parameters.class >>"
  openjdk:
    parameters:
      class:
        description: The resource class. Default is medium.
        type: enum
        enum: ["small", "medium", "medium+", "large", "xlarge"]
        default: "medium"
      version:
        description: the version of the JDK. Default is 21.0
        type: string
        default: "21.0"
      with_node:
        description: should we use the "node" version of the image
        type: boolean
        default: false
    docker:
      - image: cimg/openjdk:<< parameters.version >><<# parameters.with_node >>-node<</ parameters.with_node >>
    resource_class: << parameters.class >>
  node-lts:
    parameters:
      class:
        description: The resource class
        type: enum
        enum: ["small", "medium", "large", "xlarge"]
        default: "medium"
    docker:
      - image: cimg/node:18.16.1
    resource_class: << parameters.class >>
