apiVersion: v2
name: mongodb-migration
description: MongoDB for AM Migration Testing (Aligned with Cloud-AM)
type: application
version: 1.0.0
appVersion: "8.2.3"

dependencies:
  - name: mongodb
    version: 18.1.20
    repository: https://charts.bitnami.com/bitnami
