{{- if and (.Values.gateway.enabled) (or (not (include "gateway.externalConfig" .)) (.Values.gateway.logging.debug)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.gateway.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  {{- if not (include "gateway.externalConfig" .)}}
  gravitee.yml: |
    {{- if .Values.secrets }}
    # Kubernetes secret resolver config
    secrets:
      {{- .Values.secrets | toYaml | nindent 6 }}
    {{- end }}

    # Gateway HTTP server
    http:
    {{- if .Values.gateway.http.cookie }}
      cookie:
        secure: {{ .Values.gateway.http.cookie.secure | default false }}
        sameSite: {{ .Values.gateway.http.cookie.sameSite | default "Lax" }}
        {{- if .Values.gateway.http.cookie.session }}
        session:
          name: {{ .Values.gateway.http.cookie.session.name | default "GRAVITEE_IO_AM_SESSION" }}
          timeout: {{ .Values.gateway.http.cookie.session.timeout | default 1800000 | int }}
        {{- end }}
    {{- end }}
    {{- if .Values.gateway.http.csrf }}
      csrf:
    {{ toYaml .Values.gateway.http.csrf | nindent 8 -}}
    {{- end }}
    {{- if .Values.gateway.http.csp }}
      csp:
    {{ toYaml .Values.gateway.http.csp | nindent 8 -}}
    {{- end }}
    {{- if .Values.gateway.http.cors }}
      cors:
    {{ toYaml .Values.gateway.http.cors | nindent 8 -}}
    {{- end }}
    {{- if .Values.gateway.http.xframe }}
      xframe:
    {{ toYaml .Values.gateway.http.xframe | nindent 8 -}}
    {{- end }}
      port: {{ .Values.gateway.service.internalPort }}
      host: 0.0.0.0
      #  idleTimeout: 0
      #  tcpKeepAlive: true
      #  compressionSupported: false
      #  instances: 0
      maxHeaderSize: {{ .Values.gateway.http.maxHeaderSize }}
      maxChunkSize: {{ .Values.gateway.http.maxChunkSize }}
      maxInitialLineLength: {{ .Values.gateway.http.maxInitialLineLength }}
      maxFormAttributeSize: {{ .Values.gateway.http.maxFormAttributeSize }}
      alpn: {{ .Values.gateway.http.alpn | default "true" }}
      {{- if .Values.gateway.ssl.enabled }}
      secured: true
      ssl:
        {{- if .Values.gateway.ssl.certificateHeader }}
        certificateHeader: {{ .Values.gateway.ssl.certificateHeader }}
        {{- end }}
        keystore:
          {{- if .Values.gateway.ssl.keystore.type }}
          type: {{ .Values.gateway.ssl.keystore.type }}
          {{- end }}
          path: {{ .Values.gateway.ssl.keystore.path }}
          password: {{ .Values.gateway.ssl.keystore.password | quote }}
          {{- if .Values.gateway.ssl.keystore.kubernetes }}
          kubernetes: {{ .Values.gateway.ssl.keystore.kubernetes }}
          {{- end }}
          {{- if .Values.gateway.ssl.keystore.secret }}
          secret: {{ .Values.gateway.ssl.keystore.secret }}
          {{- end }}
          {{- if hasKey .Values.gateway.ssl.keystore "watch" }}
          watch: {{ .Values.gateway.ssl.keystore.watch }}
          {{- end }}
        clientAuth: {{ .Values.gateway.ssl.clientAuth }}
        tlsProtocols: {{ .Values.gateway.ssl.tlsProtocols }}
        {{- if .Values.gateway.ssl.ciphers }}
        ciphers: {{.Values.gateway.ssl.ciphers}}
        {{- end}}
        {{- if .Values.gateway.ssl.truststore }}
        truststore:
          {{- if .Values.gateway.ssl.truststore.type }}
          type: {{ .Values.gateway.ssl.truststore.type }}
          {{- end }}
          path: {{ .Values.gateway.ssl.truststore.path }}
          password: {{ .Values.gateway.ssl.truststore.password | quote }}
          {{- if .Values.gateway.ssl.truststore.secret }}
          secret: {{ .Values.gateway.ssl.truststore.secret }}
          {{- end }}
          {{- if hasKey .Values.gateway.ssl.truststore "watch" }}
          watch: {{ .Values.gateway.ssl.truststore.watch }}
          {{- end }}
        {{- end }}
        {{- if .Values.gateway.ssl.mtls_aliases }}
        mtls_aliases:
          {{- .Values.gateway.ssl.mtls_aliases | toYaml | nindent 10}}
        {{- end }}

      {{- end }}

    liquibase:
      enabled: {{ .Values.gateway.liquibase.enabled }}


    {{- if .Values.httpClient }}
    httpClient:
{{ toYaml .Values.httpClient | indent 6 }}
    {{- end }}

    # Sharding tags configuration
    # Allows to define inclusion/exclusion sharding tags to only deploy a part of APIs. To exclude just prefix the tag with '!'.
    tags: {{ .Values.gateway.sharding_tags }}

    services:
      core:
        http:
          enabled: {{ .Values.gateway.services.core.http.enabled | default true }}
          port: {{ .Values.gateway.services.core.http.port | default "18092" }}
          host: {{ .Values.gateway.services.core.http.host | default "localhost" }}
          authentication:
            type: {{ .Values.gateway.services.core.http.authentication.type | default "basic" }}
            users:
              admin: {{ .Values.gateway.services.core.http.authentication.password | default "adminadmin" }}
          secured: {{ .Values.gateway.services.core.http.secured | default false }}
          {{- if (eq .Values.gateway.services.core.http.secured true) }}
          ssl:
            keystore:
              type: {{ .Values.gateway.services.core.http.ssl.keystore.type }}
              path: {{ .Values.gateway.services.core.http.ssl.keystore.path }}
              {{- if .Values.gateway.services.core.http.ssl.keystore.password }}
              password: {{ .Values.gateway.services.core.http.ssl.keystore.password }}
              {{- end }}
          {{- end }}

  {{- if .Values.gateway.services }}
    {{- if .Values.gateway.services.sync }}
      sync:
{{ toYaml .Values.gateway.services.sync | indent 8 }}
    {{- end }}
  {{- end }}

      # Gateway monitoring service.
      # This service retrieves metrics like os / process / jvm metrics.
      monitoring:
        delay: 5000
        unit: MILLISECONDS

      {{- if .Values.gateway.services.metrics.enabled }}
      metrics:
        enabled: {{ .Values.gateway.services.metrics.enabled }}
        {{- if .Values.gateway.services.metrics.prometheus }}
        prometheus:
{{ toYaml .Values.gateway.services.metrics.prometheus | indent 10 }}
        {{- end }}
      {{- end }}

    {{- if ( and .Values.domains .Values.domains.secrets ) }}
    domains:
      secrets:
        {{- .Values.domains.secrets | toYaml | nindent 8 }}
    {{- end }}

    {{- if .Values.reporters }}
    reporters:
{{ toYaml .Values.reporters | indent 6 }}
    {{- end }}

    jwt:
      secret: {{ .Values.gateway.jwt.secret }}
      kid: {{ .Values.gateway.jwt.kid | default "default-gravitee-AM-key" }}
      # Allows to define the end of validity of the token in seconds (default 604800 = a week)
      expire-after: {{ .Values.gateway.jwt.expireAfter | default 604800 }}
      # Allows to define issuer (default https://gravitee.am)
      issuer: {{ .Values.gateway.jwt.issuer | default "https://gravitee.am" }}
      # Allows to define cookie context path (default /)
      cookie-path: {{ .Values.gateway.jwt.cookie.path | default "/" }}
      # Allows to define cookie domain (default "")
      {{- if .Values.gateway.jwt.cookie }}
      cookie-domain: {{ .Values.gateway.jwt.cookie.domain }}
      {{- else }}
      cookie-domain: {{ index .Values.ui.ingress.hosts 0 }}
      {{- end }}
      # Allows to define if cookie secure only (default false)
      cookie-secure: {{ .Values.gateway.jwt.cookie.secure | default false }}

    {{- if .Values.smtp }}
    # SMTP configuration used to send mails
    email:
      {{- .Values.smtp | toYaml | nindent 6 | replace "starttlsEnable" "starttls.enable" | replace "sslTrust" "ssl.trust" | replace "sslProtocols" "ssl.protocols" }}
    {{- end }}

    {{- if .Values.userManagement }}
    user:
{{ toYaml .Values.userManagement | indent 6 }}
    {{- end }}

    {{- if .Values.applications }}
    applications:
      {{- .Values.applications | toYaml | nindent 6 }}
    {{- end }}

    gateway:
      {{- if .Values.api.gateway }}
      url: {{ .Values.api.gateway.url }}
      {{- else }}
      url: https://{{index .Values.gateway.ingress.hosts 0 }}{{ .Values.gateway.ingress.path }}
      {{- end }}

{{- if .Values.gateway.cache }}
    cache:
{{ toYaml .Values.gateway.cache | indent 6}}
{{- end }}

{{- if .Values.gateway.resilience }}
    resilience:
{{ toYaml .Values.gateway.resilience | indent 6}}
{{- end }}


{{- if .Values.datasources }}
    datasources:
{{ toYaml .Values.datasources | indent 6 }}
{{- end }}

{{ include "repositories" . | indent 4}}
  {{- if .Values.gateway.consent }}
    consent:
{{ toYaml .Values.gateway.consent | indent 6  }}
  {{- end }}

    {{- if or .Values.gateway.handlers }}
    handlers:
{{ toYaml .Values.gateway.handlers | indent 6 }}
    {{- end }}
    {{- if or .Values.gateway.mfa_rate }}
    mfa_rate:
{{ toYaml .Values.gateway.mfa_rate | indent 6 }}
    {{- end }}

    # Alert Engine communication
    {{ if .Values.alerts.enabled }}
    alerts:
      alert-engine-connector-ws:
        enabled: true
      alert-engine:
        enabled: true
        {{- if .Values.alerts.engines }}
        engines:
          {{ toYaml .Values.alerts.engines | nindent 10 | trim -}}
        {{- end }}
        ws:
          discovery: true
          {{- if .Values.alerts.options }}
          {{ toYaml .Values.alerts.options | nindent 10 | trim -}}
          {{- end }}
          {{- with .Values.alerts.endpoints }}
          endpoints:
            {{ toYaml . | nindent 12 | trim -}}
          {{- end }}
          {{- if (eq .Values.alerts.security.enabled true) }}
          security:
            username: {{ .Values.alerts.security.username }}
            password: {{ .Values.alerts.security.password }}
          {{- end }}
      {{- if .Values.alerts.settings  }}
      {{ toYaml .Values.alerts.settings | nindent 6 | trim -}}
      {{- end }}
    {{- else }}
    alerts:
      alert-engine-connector-ws:
        enabled: false
    {{- end }}
  {{- end }}
    {{- if .Values.gateway.logging.debug }}
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!--
      ~ Copyright (c) 2015-2016, The Gravitee team (http://www.gravitee.io)
      ~
      ~  Licensed under the Apache License, Version 2.0 (the "License");
      ~  you may not use this file except in compliance with the License.
      ~  You may obtain a copy of the License at
      ~
      ~  http://www.apache.org/licenses/LICENSE-2.0
      ~
      ~  Unless required by applicable law or agreed to in writing, software
      ~  distributed under the License is distributed on an "AS IS" BASIS,
      ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      ~  See the License for the specific language governing permissions and
      ~  limitations under the License.
      -->

    <configuration>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            {{- if .Values.gateway.logging.stdout.json }}
            <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                <layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
                    <jsonFormatter
                            class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter">
                    </jsonFormatter>
                    <appendLineSeparator>true</appendLineSeparator>
                    <timestampFormat>yyyy-MM-dd'T'HH:mm:ss.SSSXX</timestampFormat>
                </layout>
            </encoder>
            {{- else }}
            <!-- encoders are assigned the type
                ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
            <encoder>
                <pattern>{{ .Values.gateway.logging.stdout.encoderPattern }}</pattern>
            </encoder>
            {{- end }}
        </appender>

        {{- if .Values.gateway.logging.file.enabled }}
        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>${gravitee.home}/logs/gravitee.log</file>
{{ .Values.gateway.logging.file.rollingPolicy | indent 16 }}
            <encoder>
                <pattern>{{ .Values.gateway.logging.file.encoderPattern }}</pattern>
            </encoder>
        </appender>
        {{- end }}

        {{- if .Values.gateway.logging.file.enabled }}
        <appender name="async-file" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="FILE" />
        </appender>
        {{- end }}

        <appender name="async-console" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="STDOUT" />
        </appender>

        <logger name="io.gravitee" level="{{ .Values.gateway.logging.graviteeLevel }}" />
        <logger name="com.graviteesource" level="{{ .Values.gateway.logging.graviteeSourceLevel }}" />
        <logger name="org.reflections" level="WARN" />
        <logger name="org.springframework" level="WARN" />
        {{- if .Values.gateway.logging.extraLoggers }}
{{ .Values.gateway.logging.extraLoggers | indent 8 }}
        {{- end }}

        <!-- Strictly speaking, the level attribute is not necessary since -->
        <!-- the level of the root level is set to DEBUG by default.       -->
        <root level="INFO">
            <appender-ref ref="async-console" />
            {{- if .Values.gateway.logging.file.enabled }}
            <appender-ref ref="async-file" />
            {{- end }}
        </root>

    </configuration>
  {{- end -}}
  {{- end -}}
