#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'

volumes:
  demo_am_datamongo: {}

services:
  demo_am_mongodb:
    network_mode: "bridge"
    image: mongo:3.4
    container_name: demo_gio_am_mongodb
    hostname: demo-am-mongodb
    restart: always
    volumes:
    - demo_am_datamongo:/data/db
    - ./logs/am-mongodb:/var/log/mongodb

  demo_am_gateway:
    network_mode: "bridge"
    image: graviteeio/am-gateway:latest
    container_name: demo_gio_am_gateway
    restart: always
    links:
    - demo_am_mongodb
    depends_on:
    - demo_am_mongodb
    volumes:
    - ./logs/am-gateway:/etc/gravitee.io/log
    environment:
    - gravitee_repositories_management_mongodb_uri=mongodb://demo-am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    - gravitee_repositories_oauth2_mongodb_uri=mongodb://demo-am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    - gravitee_repositories_gateway_mongodb_uri=mongodb://demo-am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    labels:
    - "traefik.backend=graviteeio-am-gateway"
    - "traefik.frontend.rule=Host:auth.gravitee.io;PathPrefixStrip:/gateway"
    - "traefik.frontend.headers.customRequestHeaders=X-Forwarded-Prefix:/gateway"
    - "traefik.port=8092"

  demo_am_management:
    network_mode: "bridge"
    image: graviteeio/am-management-api:latest
    container_name: demo_gio_am_management
    restart: always
    links:
    - demo_am_mongodb
    depends_on:
    - demo_am_mongodb
    volumes:
    - ./logs/am-management-api:/etc/gravitee.io/log
    environment:
    - gravitee_repositories_management_mongodb_uri=mongodb://demo-am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    - gravitee_repositories_oauth2_mongodb_uri=mongodb://demo-am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    - gravitee_dataPlanes_0_id=default
    - gravitee_dataPlanes_0_type=mongodb
    - gravitee_dataPlanes_0_mongodb_uri=mongodb://demo-am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    labels:
    - "traefik.backend=graviteeio-am-managementapi"
    - "traefik.frontend.rule=Host:auth.gravitee.io;PathPrefix:/management"
    - "traefik.port=8093"

  demo_am_webui:
    network_mode: "bridge"
    image: graviteeio/am-management-ui:latest
    container_name: demo_gio_am_webui
    restart: always
    depends_on:
      - demo_am_management
    environment:
      - MGMT_API_URL=https://auth.gravitee.io
      - MGMT_UI_URL=https://auth.gravitee.io
    volumes:
      - ./logs/am-webui:/var/log/httpd
    labels:
    - "traefik.backend=graviteeio-am-managementui"
    - "traefik.frontend.rule=Host:auth.gravitee.io"
    - "traefik.port=8080"
