#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  gateway:
    build:
      context: build-ctx
      args:
        - GRAVITEEAM_VERSION=${AM_VERSION}
      dockerfile: ../../../gateway/Dockerfile-dev
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:18092/_node/health?probes=jetty-http-server", "-u", "admin:adminadmin" ]
      interval: 5s
      timeout: 2s
      retries: 10
    depends_on:
      management:
        condition: service_healthy
    ports:
      - 8092:8092
      - 18092:18092
    environment:
      - GRAVITEE_EMAIL_ENABLED=true
      - GRAVITEE_EMAIL_HOST=smtp
      - GRAVITEE_EMAIL_PORT=5025
      - GRAVITEE_MFA_RATE_ENABLED=true
      - GRAVITEE_MFA_RATE_LIMIT=2
      - GRAVITEE_MFA_RATE_TIMEPERIOD=1
      - GRAVITEE_MFA_RATE_TIMEUNIT=Minutes
      - GRAVITEE_SERVICES_SYNC_CRON=*/2 * * * * *
      - GRAVITEE_SERVICES_SYNC_TIMEFRAMEBEFOREDELAY=5000
      - GRAVITEE_SERVICES_SYNC_TIMEFRAMEAFTERDELAY=5000
      - GRAVITEE_HTTP_SSL_CERTIFICATEHEADER=X-Client-Cert
      - GIO_MAX_MEM=512m
      - GRAVITEE_SERVICES_CORE_HTTP_HOST=0.0.0.0

  management:
    build:
      context: build-ctx
      args:
        - GRAVITEEAM_VERSION=${AM_VERSION}
      dockerfile: ../../../management-api/Dockerfile-dev
    healthcheck:
      test: ["CMD", "curl", "http://localhost:18093/_node/health?probes=jetty-http-server", "-u", "admin:adminadmin"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - 8093:8093
    environment:
      - GRAVITEE_EMAIL_ENABLED=true
      - GRAVITEE_EMAIL_HOST=smtp
      - GRAVITEE_EMAIL_PORT=5025
      - GRAVITEE_MFA_RATE_ENABLED=true
      - GRAVITEE_MFA_RATE_LIMIT=2
      - GRAVITEE_MFA_RATE_TIMEPERIOD=1
      - GRAVITEE_MFA_RATE_TIMEUNIT=Minutes
      - GIO_MAX_MEM=512m

  am-wait:
    image: curlimages/curl:8.10.1
    depends_on:
      management:
        condition: service_healthy
      gateway:
        condition: service_healthy

  smtp:
    image: gessnerfl/fake-smtp-server:1.10.4
    ports:
      - 5080:5080
      - 5025:5025

  wiremock:
    image: wiremock/wiremock:3.13.1
    command: ["--verbose", "--global-response-templating"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/mappings"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - 8181:8080

  wiremock-init:
    image: curlimages/curl:8.10.1
    depends_on:
      wiremock:
        condition: service_healthy
    volumes:
      - ./wiremock/request.json:/tmp/request.json
    command: "curl -X POST http://wiremock:8080/__admin/mappings -d @/tmp/request.json -H 'Content-Type: application/json'"

  ciba:
    image: gravitee-am-ciba-delegated-service
    ports:
      - 8080:8080

  openfga:
    image: openfga/openfga:v1.8.5
    ports:
      - 8090:8080
      - 8091:8081
    command: ["run", "--playground-enabled=false"]

  gateway-mtls:
    image: nginx:1.21.1-alpine
    restart: always
    volumes:
      - ./gateway-mtls/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway-mtls/server/server.crt:/etc/nginx/certs/server.crt:ro
      - ./gateway-mtls/server/server.key:/etc/nginx/certs/server.key:ro
      - ./gateway-mtls/server/ca.crt:/etc/nginx/certs/ca.crt:ro
    ports:
      - 1443:1443
